---

- name: make {{ omada_dir }}install.sh exicutable
  ansible.builtin.file:
    path: "{{ omada_dir }}/install.sh"
    mode: a+x

- name: Install Omada
  ansible.builtin.command: "./install.sh -y -n"
  args:
    chdir: "{{ omada_dir }}"
  register: omadainstall
  when: omada_preset.rc == 1

- name: omada install status
  ansible.builtin.debug:
    msg: "{{ omadainstall.stdout_lines }}"
  when: omada_preset.rc == 1

- name: make sure Omada is runnig.
  ansible.builtin.service:
    name: tpeap
    state: started
    enabled: true

- name: Omada install check
  ansible.builtin.command: which tpeap
  failed_when: false
  changed_when: false
  check_mode: false
  register: omada_done

- name: omada install status
  ansible.builtin.debug:
    msg: "{{ omada_done.stdout_lines }}"
  when: omada_preset.rc == 1

- name: Reboot
  ansible.builtin.reboot:
    post_reboot_delay: 30
  when: reboot_required.stat.exists

- name: Get my public IP
  community.general.ipify_facts:
  register: ip

- name: url
  ansible.builtin.debug:
    msg: "Omada Controller is running at http://{{ ipify_public_ip }}:8088"
