---
name: Ansible Lint

'on': [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: ansible-lint
    steps:
      - name: checkout codebase
        uses: actions/checkout@master

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: install dependencies
        run: pip3 install ansible ansible-lint yamllint

      - name: check ansible-lint version
        run: ansible-lint --version

      - name: lint
        run: |
          ansible-lint .
          yamllint .
